from typing import Any, List, Tuple
def _tensor_add(a: Any, b: Any) -> Any: ...
def _tensor_mul(a: Any, b: Any) -> Any: ...
def _tensor_matmul(a: Any, b: Any) -> Any: ...
def _conv2d_forward(input: Any, weight: Any, bias: Any, stride: int, padding: int) -> Any: ...
def _batch_norm(input: Any, mean: Any, var: Any, weight: Any, bias: Any) -> Any: ...
